### ISSUE TITLE
Problem starting node

### ISSUE THREAD

**Issue by acka47** [hbz/swib18-workshop#10]
```
$ npm start

> swib18-workshop@0.0.1 start /home/acka47/git/swib18-workshop
> node js/app.js

/home/acka47/git/swib18-workshop/js/app.js:12
request(options, (error, response, body) => {
                                         ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Linux 4.4.0-137-generic
npm ERR! argv "/home/acka47/.nvm/versions/node/v0.12.18/bin/node" "/home/acka47/.nvm/versions/node/v0.12.18/bin/npm" "start"
npm ERR! node v0.12.18
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! swib18-workshop@0.0.1 start: `node js/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swib18-workshop@0.0.1 start script 'node js/app.js'.
npm ERR! This is most likely a problem with the swib18-workshop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node js/app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs swib18-workshop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls swib18-workshop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/acka47/git/swib18-workshop/npm-debug.log
```

**Comment by acka47** [comment]
In now updated the node version:

```
 $ node -v
v10.11.0
```

Now I get another error:

```
$ npm start

> swib18-workshop@0.0.1 start /home/acka47/git/swib18-workshop
> node js/app.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/acka47/git/swib18-workshop/js/app.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swib18-workshop@0.0.1 start: `node js/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swib18-workshop@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by fsteeg** [comment]
After running `npm install` again with the newer node version it worked, closing.
