### ISSUE TITLE
Problems installing node dependencies

### ISSUE THREAD

**Issue by acka47** [hbz/swib18-workshop#25]
Node and npm version:

```
$ node -v
v11.0.0
$ npm -v
6.4.1
```

Error:

```
$ sudo npm install
[sudo] Passwort für acka47: 

> rdf-canonize@0.2.4 install /home/acka47/git/swib18-workshop/node_modules/rdf-canonize
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/acka47/git/swib18-workshop/node_modules/rdf-canonize/build'
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/acka47/git/swib18-workshop/node_modules/rdf-canonize
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rdf-canonize@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rdf-canonize@0.2.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/acka47/.npm/_logs/2018-10-25T18_52_14_771Z-debug.log
```
I also tried it with node v8.9.0, same error.

**Comment by acka47** [comment]
I tried it with the current master branch as well as with "5-kibana".

**Comment by acka47** [comment]
I got quite frustrated. Tried a lot of stuff, e.g. the proposed solutions in https://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo/24404451. In the end I stumbled over https://github.com/nodejs/node-gyp/issues/809#issuecomment-265611513 and that did it for me: `sudo apt install g++`

**Comment by acka47** [comment]
Thinking about it, `sudo apt install g++` wasn't the whole solution. THe things I did before resolved the EACCES problem, after that I got a different error message which was then resolved by g++ install:

```
$ npm install

> rdf-canonize@0.2.4 install /home/acka47/git/swib18-workshop/node_modules/rdf-canonize
> node-gyp rebuild

make: Verzeichnis „/home/acka47/git/swib18-workshop/node_modules/rdf-canonize/build“ wird betreten
  CXX(target) Release/obj.target/urdna2015/lib/native/IdentifierIssuer.o
make: g++: Befehl nicht gefunden
urdna2015.target.mk:111: die Regel für Ziel „Release/obj.target/urdna2015/lib/native/IdentifierIssuer.o“ scheiterte
make: *** [Release/obj.target/urdna2015/lib/native/IdentifierIssuer.o] Fehler 127
make: Verzeichnis „/home/acka47/git/swib18-workshop/node_modules/rdf-canonize/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/acka47/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/home/acka47/.nvm/versions/node/v11.0.0/bin/node" "/home/acka47/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/acka47/git/swib18-workshop/node_modules/rdf-canonize
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rdf-canonize@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rdf-canonize@0.2.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/acka47/.npm/_logs/2018-10-26T20_42_36_140Z-debug.log
```
